language: java
jdk: openjdk8

notifications:
  email:
    on_success: always
    on_failure: always

cache:
 directories:
   ~/.gradle/caches/
   ~/.gradle/wrapper/

jobs:
  include:
    - stage: compile
      script: gradle compileJava
    - stage: test
      script: gradle test
    - stage: jar
      script: gradle jar
    - stage: deploy
      script: openssl aes-256-cbc -K $encrypted_123poi456qwe_key -iv $encrypted_123poi456qwe_iv -in deploy_rsa.enc -out /tmp/deploy_rsa -d
      script: eval "$(ssh-agent -s)"
      script: chmod 600 /tmp/deploy_rsa
      script: ssh-add /tmp/deploy_rsa
      script: rsync -r --delete-after --quiet $TRAVIS_BUILD_DIR/build/libs root@206.81.16.40:/opt

addons:
  ssh_known_hosts: 206.81.16.40