jobs:
  include:
    - language: node_js
      os: linux
      node_js: 10.9.0
      before_script:
        - cd moneytransfer-ui
        - npm install
      script:
        - npm run lint
        - npm run test
        - npm run build
      deploy:
        - provider: script
          cleanup: false
          script: rsync --recursive --delete --quiet $TRAVIS_BUILD_DIR/moneytransfer-ui/dist/ root@206.81.16.40:/var/www/html/moneytransfer/public
          on:
            branch: unit-testing

    - language: java
      os: linux
      jdk: openjdk8
      install: true
      script:
        - ./gradlew build
      deploy:
        - provider: script
          cleanup: false
          script: rsync --recursive --delete --quiet $TRAVIS_BUILD_DIR/moneytransfer-api/build/libs/ root@206.81.16.40:/opt/apps/money-transfer
          on:
            branch: unit-testing
      after_deploy:
        - scripts/run.sh

addons:
  ssh_known_hosts: 206.81.16.40

before_deploy:
- openssl aes-256-cbc -K $encrypted_6d54636b4ab4_key -iv $encrypted_6d54636b4ab4_iv -in $TRAVIS_BUILD_DIR/deploy_rsa.enc -out /tmp/deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/deploy_rsa
- ssh-add /tmp/deploy_rsa

cache:
  directories:
  - $HOME/.gradle/caches/
  - $HOME/.gradle/wrapper/

notifications:
  email:
    on_success: always
    on_failure: always