language: java
jdk: openjdk8

notifications:
  email:
    on_success: always
    on_failure: always

cache:
 directories:
   ~/.gradle/caches/
   ~/.gradle/wrapper/

jobs:
  include:
    - stage: compile
      script: gradle compileJava
    - stage: test
      script: gradle test
    - stage: jar
      script: gradle jar