language: java
jdk: openjdk8

notifications:
  email:
    on_success: always
    on_failure: always

cache:
 directories:
   - ~/.gradle/caches/
   - ~/.gradle/wrapper/
   - ~/moneytransfer-ui/node_modules

addons:
  ssh_known_hosts: 206.81.16.40

jobs:
  include:
    - stage: test
      script: gradle test
    - stage: compile
      script: gradle compileJava
    - stage: jar
      script: gradle jar -Pinclude-ui
    - stage: before_deploy
      if: branch = master
      script: openssl aes-256-cbc -K $encrypted_6d54636b4ab4_key -iv $encrypted_6d54636b4ab4_iv -in deploy_rsa.enc -out /tmp/deploy_rsa -d
      script: eval "$(ssh-agent -s)"
      script: chmod 600 /tmp/deploy_rsa
      script: ssh-add /tmp/deploy_rsa
    - stage: deploy
      provider: script
      skip_cleanup: true
      script: rsync -r --delete-after --quiet $TRAVIS_BUILD_DIR/build/libs/ root@206.81.16.40:/opt/apps/money-transfer
    - stage: after_deploy
      script: scripts/run_application.sh